// Command rangegen builds final-draw range histograms from hosted sample logs.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/nuttakit/2-7-bot/internal/arena"
	"github.com/nuttakit/2-7-bot/internal/cards"
	"github.com/nuttakit/2-7-bot/internal/deuce"
)

func main() {
	matches := flag.String("matches", "bin/matches.json", "arena matches --json output")
	dir := flag.String("hands", "bin/swit-samples", "sample logs named MATCH-HAND.json")
	target := flag.String("target", "swit-27td-5.1-i048", "opponent name in match metadata")
	out := flag.String("out", "", "Go output; defaults to the selected model's table file")
	responses := flag.Bool("responses", false, "generate river response policy histograms instead of final-hand ranges")
	policy := flag.Bool("policy", false, "export opponent decision features as JSON for offline model fitting")
	flag.Parse()
	if *responses && *policy {
		fmt.Fprintln(os.Stderr, "choose only one output mode")
		os.Exit(2)
	}
	gen := generate
	if *responses {
		gen = generateResponses
	}
	if *policy {
		gen = generatePolicy
	}
	if *out == "" {
		*out = "internal/onyx/ranges_table.go"
		if *responses {
			*out = "internal/onyx/river_response_table.go"
		}
		if *policy {
			*out = "bin/onyx-policy-samples.json"
		}
	}
	if err := gen(*matches, *dir, *target, *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(matches, dir, target, out string) error {
	data, err := os.ReadFile(matches)
	if err != nil {
		return err
	}
	var ms []arena.MatchSummary
	if err := json.Unmarshal(data, &ms); err != nil {
		return err
	}
	seats := map[int]int{}
	for _, m := range ms {
		for p, name := range m.Players {
			if name == target {
				seats[m.ID] = p
			}
		}
	}
	files, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return err
	}
	var counts [16]map[uint32]int
	for i := range counts {
		counts[i] = map[uint32]int{}
	}
	used := 0
	for _, path := range files {
		id, err := strconv.Atoi(strings.Split(filepath.Base(path), "-")[0])
		if err != nil {
			return err
		}
		seat, ok := seats[id]
		if !ok {
			return fmt.Errorf("missing target in match %d", id)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var h arena.HandDetail
		if err := json.Unmarshal(data, &h); err != nil {
			return err
		}
		bets, err := riverBets(h, seat)
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		for _, bet := range bets {
			counts[bet.context][uint32(bet.value)]++
		}
		value, current, previous, ok, err := finalHand(h, seat)
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		if !ok {
			continue
		}
		counts[min(current, 3)][uint32(value)]++
		counts[4+min(previous, 3)][uint32(value)]++
		used++
	}
	if used == 0 {
		return fmt.Errorf("no final-draw samples")
	}
	var text strings.Builder
	fmt.Fprintf(&text, "// Code generated by cmd/rangegen. DO NOT EDIT.\n// %d sampled final hands against %s; sampling uncertainty remains.\npackage onyx\n\nvar rangeData = [16][]weightedValue{\n", used, target)
	for _, histogram := range counts {
		keys := make([]uint32, 0, len(histogram))
		for k := range histogram {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
		text.WriteString("{\n")
		for _, k := range keys {
			fmt.Fprintf(&text, "{%d,%d},\n", k, histogram[k])
		}
		text.WriteString("},\n")
	}
	text.WriteString("}\n")
	formatted, err := format.Source([]byte(text.String()))
	if err != nil {
		return err
	}
	return os.WriteFile(out, formatted, 0644)
}

type riverBet struct {
	value   deuce.Value
	context int
}

func riverBets(h arena.HandDetail, seat int) ([]riverBet, error) {
	var hand []cards.Card
	var out []riverBet
	counts := [2]int{-1, -1}
	for _, e := range h.Events {
		if e.Player == nil || *e.Player < 0 || *e.Player > 1 {
			continue
		}
		if e.Kind == "replacement" && e.Street != nil && *e.Street == "draw3" && e.Cards != nil {
			counts[*e.Player] = len(*e.Cards) / 2
		}
		if *e.Player != seat {
			continue
		}
		switch e.Kind {
		case "initial-cards":
			if e.Cards == nil {
				return nil, fmt.Errorf("missing initial cards")
			}
			var err error
			hand, err = packed(*e.Cards)
			if err != nil {
				return nil, err
			}
		case "replacement":
			if e.Cards == nil || e.Detail == nil {
				return nil, fmt.Errorf("incomplete replacement")
			}
			in, err := packed(*e.Cards)
			if err != nil {
				return nil, err
			}
			discard, err := packed(*e.Detail)
			if err != nil {
				return nil, err
			}
			hand = cards.With(cards.Without(hand, discard), in)
		case "action":
			if e.Street == nil || *e.Street != "draw3" || e.Action == nil || (*e.Action != "bet" && *e.Action != "raise") {
				continue
			}
			if counts[0] < 0 || counts[1] < 0 || len(hand) != 5 || cards.NewSet(hand).Len() != 5 {
				return nil, fmt.Errorf("invalid river betting sample")
			}
			context := 8
			if counts[seat] > 0 {
				context += 2
			}
			if counts[1-seat] > 0 {
				context++
			}
			if *e.Action == "raise" {
				context += 4
			}
			out = append(out, riverBet{deuce.Eval(hand), context})
		}
	}
	return out, nil
}

func packed(text string) ([]cards.Card, error) {
	if len(text)%2 != 0 {
		return nil, fmt.Errorf("odd card string")
	}
	hand := make([]cards.Card, 0, len(text)/2)
	for i := 0; i < len(text); i += 2 {
		c, err := cards.ParseCard(text[i : i+2])
		if err != nil {
			return nil, err
		}
		hand = append(hand, c)
	}
	return hand, nil
}

// Read only one observation per hand: repeated betting actions must not
// overweight strong hands that raise. Both draw counts must be observed.
func finalHand(h arena.HandDetail, seat int) (deuce.Value, int, int, bool, error) {
	var hand []cards.Card
	previous, current := -1, -1
	for _, e := range h.Events {
		if e.Player == nil || *e.Player != seat {
			continue
		}
		switch e.Kind {
		case "initial-cards":
			if e.Cards == nil {
				return 0, 0, 0, false, fmt.Errorf("missing initial cards")
			}
			var err error
			hand, err = packed(*e.Cards)
			if err != nil {
				return 0, 0, 0, false, err
			}
		case "replacement":
			if e.Cards == nil || e.Detail == nil || e.Street == nil {
				return 0, 0, 0, false, fmt.Errorf("incomplete replacement")
			}
			in, err := packed(*e.Cards)
			if err != nil {
				return 0, 0, 0, false, err
			}
			out, err := packed(*e.Detail)
			if err != nil {
				return 0, 0, 0, false, err
			}
			hand = cards.With(cards.Without(hand, out), in)
			if *e.Street == "draw2" {
				previous = len(in)
			}
			if *e.Street == "draw3" {
				current = len(in)
			}
		case "action":
			if e.Street != nil && *e.Street == "draw3" && current >= 0 && previous >= 0 {
				if len(hand) != 5 || cards.NewSet(hand).Len() != 5 {
					return 0, 0, 0, false, fmt.Errorf("invalid final hand")
				}
				return deuce.Eval(hand), current, previous, true, nil
			}
		}
	}
	return 0, 0, 0, false, nil
}
