package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/nuttakit/2-7-bot/internal/arena"
	"github.com/nuttakit/2-7-bot/internal/cards"
	"github.com/nuttakit/2-7-bot/internal/deuce"
)

type riverResponseSample struct {
	context, response int
	value             deuce.Value
}

// Responses 0..2 are fold/call/raise facing hero's opening river bet.
// Responses 3..4 are check/bet after hero checked from the big blind.
// Later replies to raises are deliberately excluded.
func riverResponses(h arena.HandDetail, target int) ([]riverResponseSample, error) {
	if target < 0 || target > 1 || len(h.Hand.Roles) != 2 {
		return nil, fmt.Errorf("invalid river response seats")
	}
	var hand []cards.Card
	counts := [2]int{-1, -1}
	wagers := 0
	heroChecked, heroBet := false, false
	var out []riverResponseSample
	for _, e := range h.Events {
		if e.Player == nil || *e.Player < 0 || *e.Player > 1 {
			continue
		}
		p := *e.Player
		if p == target && e.Kind == "initial-cards" {
			if e.Cards == nil {
				return nil, fmt.Errorf("missing target cards")
			}
			var err error
			hand, err = packed(*e.Cards)
			if err != nil {
				return nil, err
			}
		}
		if e.Kind == "replacement" {
			if e.Cards == nil || e.Detail == nil {
				return nil, fmt.Errorf("missing replacement")
			}
			in, err := packed(*e.Cards)
			if err != nil {
				return nil, err
			}
			discard, err := packed(*e.Detail)
			if err != nil {
				return nil, err
			}
			if p == target {
				hand = cards.With(cards.Without(hand, discard), in)
			}
			if e.Street != nil && *e.Street == "draw3" {
				counts[p] = len(in)
			}
		}
		if e.Kind != "action" || e.Street == nil || *e.Street != "draw3" || e.Action == nil {
			continue
		}
		a := *e.Action
		response := -1
		if p == target {
			if wagers == 1 && heroBet {
				switch a {
				case "fold":
					response = 0
				case "call":
					response = 1
				case "raise":
					response = 2
				}
			} else if wagers == 0 && heroChecked && h.Hand.Roles[1-target] == "bigblind" {
				switch a {
				case "check":
					response = 3
				case "bet":
					response = 4
				}
			}
			if response >= 0 {
				if counts[0] < 0 || counts[1] < 0 || len(hand) != 5 || cards.NewSet(hand).Len() != 5 {
					return nil, fmt.Errorf("incomplete river response")
				}
				context := min(counts[target], 2) * 4
				if counts[1-target] > 0 {
					context += 2
				}
				if h.Hand.Roles[1-target] == "smallblind" {
					context++
				}
				out = append(out, riverResponseSample{context, response, deuce.Eval(hand)})
			}
		} else {
			if wagers == 0 && a == "check" {
				heroChecked = true
			}
			if wagers == 0 && a == "bet" {
				heroBet = true
			}
		}
		if a == "bet" || a == "raise" {
			wagers++
		}
	}
	return out, nil
}

func generateResponses(metadata, dir, target, out string) error {
	raw, err := os.ReadFile(metadata)
	if err != nil {
		return err
	}
	var matches []arena.MatchSummary
	if err = json.Unmarshal(raw, &matches); err != nil {
		return err
	}
	seats := map[int]int{}
	for _, m := range matches {
		if len(m.Players) == 2 {
			for p, name := range m.Players {
				if name == target {
					seats[m.ID] = p
				}
			}
		}
	}
	files, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return err
	}
	var data [12][5]map[uint32]int
	for c := range data {
		for a := range data[c] {
			data[c][a] = map[uint32]int{}
		}
	}
	used := 0
	for _, path := range files {
		id, err := strconv.Atoi(strings.Split(filepath.Base(path), "-")[0])
		if err != nil {
			return err
		}
		seat, ok := seats[id]
		if !ok {
			return fmt.Errorf("missing target in match %d", id)
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var h arena.HandDetail
		if err = json.Unmarshal(raw, &h); err != nil {
			return err
		}
		samples, err := riverResponses(h, seat)
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		for _, s := range samples {
			data[s.context][s.response][uint32(s.value)]++
			used++
		}
	}
	if used == 0 {
		return fmt.Errorf("no river responses")
	}
	var s strings.Builder
	fmt.Fprintf(&s, "// Code generated by cmd/rangegen -responses. DO NOT EDIT.\n// %d observed river responses; empirical policy estimates, not solved ranges.\npackage onyx\nvar riverResponseData = [12][5][]weightedValue{\n", used)
	for _, context := range data {
		s.WriteString("{\n")
		for _, hist := range context {
			keys := make([]uint32, 0, len(hist))
			for v := range hist {
				keys = append(keys, v)
			}
			sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
			s.WriteString("{\n")
			for _, v := range keys {
				fmt.Fprintf(&s, "{%d,%d},\n", v, hist[v])
			}
			s.WriteString("},\n")
		}
		s.WriteString("},\n")
	}
	s.WriteString("}\n")
	formatted, err := format.Source([]byte(s.String()))
	if err != nil {
		return err
	}
	return os.WriteFile(out, formatted, 0644)
}
